name: toy-compiler

dependencies:
  - base
  - text
  - array
  - mtl
  - containers
  - transformers
  - prettyprinter

ghc-options:
  -Wall
  -fwarn-missing-signatures

executables:
  toy-compiler:
    main: Main.hs

source-dirs:
  - src