name: toy-compiler

dependencies:
  - base
  - text
  - array
  - mtl
  - containers
  - transformers
  - prettyprinter

ghc-options:
  -Wall
  -fwarn-missing-signatures

# For some reason, uncommenting the build-tools related lines prevents Cabal
# from finding the alex and happy executables when building. However, enabling
# them in nix-shell is fine...

# build-tools:
#   - alex
#   - happy

executables:
  smhihs:
    main: Main.hs

source-dirs:
  - src